### ISSUE TITLE
Support edited event

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/actions-suggest-related-links#4]
### Is your feature request related to a problem? Please describe

```yaml
on:
  issues:
    types:
      - opened
      - edited
```

### Describe the solution you'd like

When the edited event is triggered, suggested links are updated.

### Describe alternatives you've considered

N/A

### Additional context

N/A
