### ISSUE TITLE
Support only-labels input option

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/actions-suggest-related-links#6]
### Is your feature request related to a problem? Please describe

```yaml
  only-labels:
    description: 'Only issues with all of these labels are the target of suggestion. Defaults to `[]` (disabled) and can be a comma-separated list of labels.'
    default: ''
```

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

### Additional context

- https://github.com/actions/stale/blob/1849651e2aa1b1d6d2cba4c90c719f4b6c929a28/action.yml
